apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1.0.0
  labels:
    app: my-app
    version: 1.0.0
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers: 
      - name: app-flask
        image: app-flask:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: 
          limits:
            memory: "256Mi" # 256MB
            cpu: "200m"     # 200milli cpu (.2 cpu or 20% of cpu)

